force-app/main/default/objects/Account/fields/Account_Owner_Approver__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Account_Owner_Requester__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Requester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner Requester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Requestor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending For Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Initiated from contact admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Branch object</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <label>FEIN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IBuyFast_Manual_Auto__c.field-meta.xml
<CustomField>
    <fullName>IBuyFast_Manual_Auto__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IBuyFast-Manual/Auto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VRD_Level__c.field-meta.xml
<CustomField>
    <fullName>VRD_Level__c</fullName>
    <label>VRD Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level  2</fullName>
            </value>
            <value>
                <fullName>Level  3</fullName>
            </value>
            <value>
                <fullName>Level  5</fullName>
            </value>
            <value>
                <fullName>Level  6</fullName>
            </value>
            <value>
                <fullName>Level  7</fullName>
            </value>
            <value>
                <fullName>Level  8</fullName>
            </value>
            <value>
                <fullName>Level  9</fullName>
            </value>
            <value>
                <fullName>Level  10</fullName>
            </value>
            <value>
                <fullName>Level  11</fullName>
            </value>
            <value>
                <fullName>Level  12</fullName>
            </value>
            <value>
                <fullName>Level  13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/SubmitContractAdminController.cls
public without sharing class SubmitContractAdminController {
    
    public class checkMedatoryFieldAccount{
        @AuraEnabled public Boolean allMandatoryFilled;
        @AuraEnabled public String mandatoryFields;
         public checkMedatoryFieldAccount(){}
         
    }
    @AuraEnabled(cacheable=true)
	public static checkMedatoryFieldAccount getCurrentAccount(Id accountId) {
        checkMedatoryFieldAccount objCFA = new checkMedatoryFieldAccount();
        objCFA.allMandatoryFilled = true;
        objCFA.mandatoryFields = '';
        system.debug('Current Account Id  '+accountId);
        Boolean allMandatoryFilled =  True;
		Account objCurrentAcc = [SELECT Id, Name, Branch__c, VRD_Level__c, Phone, FEIN__c, IBuyFast_Manual_Auto__c,
                                 		ShippingStreet, ShippingCity, ShippingState, ShippingCountry, 
                                 		ShippingPostalCode
                                 FROM Account
                                 WHERE Id =: accountId Limit 1];
       
       system.debug('objCurrentAcc '+ objCurrentAcc);
        if(objCurrentAcc.Branch__c == Null ){
            allMandatoryFilled = False;   
             system.debug('objCurrentAcc 1');
            objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='Branch';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Branch';
            }
        	
        }
       /* if(objCurrentAcc.IBuyFast_Manual_Auto__c == Null ){
             allMandatoryFilled = False;
            system.debug('objCurrentAcc 2');
            objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='IBuyFast Manual/Auto';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'IBuyFast Manual/Auto';
            }
        	
        }*/
        /*if(objCurrentAcc.Name == Null || objCurrentAcc.Name == ''){
             allMandatoryFilled = False;
            system.debug('objCurrentAcc 3');
            objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='Name';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Name';
            }
        }*/
        	
        if(objCurrentAcc.FEIN__c == Null || objCurrentAcc.FEIN__c == '' ){
             allMandatoryFilled = False;
            system.debug('objCurrentAcc 4');
            objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='FEIN';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'FEIN';
            }        	
        }
        if(objCurrentAcc.VRD_Level__c == Null || objCurrentAcc.VRD_Level__c == ''){
            allMandatoryFilled = False;
            system.debug('objCurrentAcc 5');
            objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='VRD Level';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'VRD Level';
            }    	
        }
        if(objCurrentAcc.Phone == Null || objCurrentAcc.Phone == ''){
            allMandatoryFilled = False;
            system.debug('objCurrentAcc 6');
            objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='Phone';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Phone';
            }         	
        }       
        if(objCurrentAcc.ShippingStreet == Null || objCurrentAcc.ShippingStreet == ''){
            allMandatoryFilled = False;
            system.debug('objCurrentAcc 7');
            objCFA.allMandatoryFilled = False;
             if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='Shipping Street';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Shipping Street';
            }   
        	//objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Shipping Street';
        } 
        if(objCurrentAcc.ShippingCity == Null || objCurrentAcc.ShippingCity == ''){
            allMandatoryFilled = False;
            system.debug('objCurrentAcc 8');
             objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='Shipping City';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Shipping City';
            }   
        	//objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'ShippingCity';
        } 
        if(objCurrentAcc.ShippingState == Null || objCurrentAcc.ShippingState == ''){
            allMandatoryFilled = False;
            system.debug('objCurrentAcc 10');
            objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='Shipping State';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Shipping State';
            }   
        	//objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'ShippingState';
        } 
        if(objCurrentAcc.ShippingCountry == Null || objCurrentAcc.ShippingCountry == ''){
            allMandatoryFilled = False;
            system.debug('objCurrentAcc 9');
             objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='Shipping Country';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Shipping Country';
            }   
        	//objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'ShippingCountry';
        } 
        
        if(objCurrentAcc.ShippingPostalCode == Null || objCurrentAcc.ShippingPostalCode == ''){
            allMandatoryFilled = False;
            system.debug('objCurrentAcc 11');
             objCFA.allMandatoryFilled = False;
            if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='Shipping PostalCode';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'Shipping PostalCode';
            }  
        	//objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'ShippingPostalCode';
        } 
        
        List<ContentDocumentLink> listCDL = [SELECT ContentDocumentId, Id, IsDeleted, LinkedEntityId, ShareType,
                                  		 	SystemModstamp, Visibility 
                                  	FROM ContentDocumentLink 
                                  	WHERE LinkedEntityId =:objCurrentAcc.Id];
      List<Id> lstContentDocumentlist = new List<Id>();
      for(ContentDocumentLink objCDL : listCDL){
          lstContentDocumentlist.add(objCDL.ContentDocumentId);
      }
       system.debug('lstContentDocumentlist '+lstContentDocumentlist);
      list<ContentVersion> listCV = new list<ContentVersion>();
       ContentDocument objCD = new ContentDocument();
      if(!listCDL.isEmpty()){
         	listCV = [SELECT Checksum, ContentBodyId, ContentDocumentId, ContentLocation, ContentModifiedById,
                   		  ContentModifiedDate, ContentSize, ContentUrl, CreatedById, CreatedDate, Description, Document_Type__c,
                   		  ExternalDataSourceId, ExternalDocumentInfo1, ExternalDocumentInfo2, FeaturedContentBoost,
                   		  FeaturedContentDate, FileExtension, FileType, FirstPublishLocationId, Id, IsAssetEnabled,
                   		  IsDeleted, IsLatest, IsMajorVersion, LastModifiedById, LastModifiedDate, NegativeRatingCount,
                   		  Origin, OwnerId, PathOnClient, PositiveRatingCount, PublishStatus, RatingCount, ReasonForChange,
                   		  SharingOption,SharingPrivacy,SystemModstamp,TagCsv,TextPreview,Title,VersionData, VersionNumber 
                   FROM ContentVersion
                   WHERE Document_Type__c = 'W-9'AND ContentDocumentId IN : lstContentDocumentlist Order By LastModifiedDate DESC  Limit 1];
     }
      system.debug('listCV '+listCV);  
      if(listCV.isEmpty() ){
        	allMandatoryFilled = False;
            system.debug('objCurrentAcc 13');
            objCFA.allMandatoryFilled = False;
          if(objCFA.mandatoryFields == ''){
                 objCFA.mandatoryFields ='please upload W9 Document through W9 Attachment button';
            }else{
                objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'please upload W9 Document through W9 Attachment button';
            }  
        	//objCFA.mandatoryFields =  objCFA.mandatoryFields+', <BR />'+ 'please Upload W9 Document';
      }
     
       system.debug('objCFA '+ objCFA);
       //return allMandatoryFilled;
       return objCFA;
		
	}
    @AuraEnabled(cacheable=False)
    public static void submitApprovalProcess(String currentRecordId){
        String accountId = currentRecordId;
        Account upAcc = [Select Id, Account_Owner_Approver__c,Account_Owner_Requester__c,Approval_Status__c From Account WHERE Id =:accountId ];
        
        String userId = userInfo.getUserId();
            User logedInUser =[SELECT ManagerId FROM User where Id =: userId Limit 1];
        upAcc.Account_Owner_Approver__c = logedInUser.ManagerId;
        upAcc.Account_Owner_Requester__c = logedInUser.Id;
        upAcc.Approval_Status__c = 'Initiated from contact admin';
        update upAcc;
            Approval.ProcessSubmitRequest appReq = new Approval.ProcessSubmitRequest();
        	appReq.setComments('Submitting request for approval.');
        	appReq.setObjectId(accountId);
            appReq.setSubmitterId(upAcc.Account_Owner_Requester__c); 
            appReq.setProcessDefinitionNameOrId('SubmitContractAdminApproval');
        	appReq.setSkipEntryCriteria(true);            
            appReq.setNextApproverIds(new Id[] {upAcc.Account_Owner_Approver__c});
            Approval.ProcessResult result = Approval.process(appReq); 
    }
    @AuraEnabled(cacheable=false)
	public static void updateContentVersion(Id accountId, string documentId) {
       ContentVersion objConVer = [SELECT ContentBodyId,ContentDocumentId,ContentUrl,Document_Type__c,VersionData,VersionNumber 
        							FROM ContentVersion 
        							WHERE ContentDocumentId =: documentId];
        objConVer.Document_Type__c = 'W-9';
        system.debug(' objConVer '+objConVer);
        update objConVer;
    }
}