force-app/main/default/objects/Account/fields/BI_ID__c.field-meta.xml
<CustomField>
    <fullName>BI_ID__c</fullName>
    <description>This is placeholder for a BI related ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is placeholder for a BI related ID.</inlineHelpText>
    <label>BI ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Branch object</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Number__c</fullName>
    <description>Branch Number</description>
    <externalId>true</externalId>
    <label>Branch Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Primary Phone number for the Branch location</description>
    <inlineHelpText>Primary Phone number for the Branch location</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Branch_number__c.field-meta.xml
<CustomField>
    <fullName>Branch_number__c</fullName>
    <description>Admin Branch Number</description>
    <inlineHelpText>Admin Branch Number</inlineHelpText>
    <label>Branch number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Buyer_ID__c.field-meta.xml
<CustomField>
    <fullName>Buyer_ID__c</fullName>
    <description>Buyer&apos;s ASAP ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Buyer&apos;s ASAP ID</inlineHelpText>
    <label>Buyer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Payment_Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Branch_Number__c</fullName>
    <description>User Story 500528: Stock/Stock Bid Fields for Lookup Association</description>
    <label>Payment Branch Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>Provider_ID__c</fullName>
    <description>Provider&apos;s ASAP ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Provider&apos;s ASAP ID</inlineHelpText>
    <label>Provider ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock_Bid__c.field-meta.xml
<CustomField>
    <fullName>Stock_Bid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Bid</label>
    <referenceTo>Stock_Bid__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StockAccountAssociationBatch_Test.cls
@isTest
public class StockAccountAssociationBatch_Test {
    static testMethod void testMethod2(){
        Stock_bid__c stkBid = new Stock_bid__c();
        stkBid.Stock__c = 'test123';
        insert stkBid;
        
        Branch__c objBranch = new Branch__c(Phone__c = '18293819', Branch_Number__c = '2123');
        insert objBranch;
        List<Stock__c> lstStk = new List<Stock__c>();
        
        
        Stock__c stk1 = new Stock__c();
        stk1.Name = 'test123';
        stk1.Buyer_ID__c = 'BUY-5566';
        stk1.Payment_Branch_Number__c = '2123';
        lstStk.add(stk1);
        
        Stock__c stk2 = new Stock__c();
        stk2.Provider_ID__c ='PRO-1122';
        lstStk.add(stk2);
        
        Stock__c stk21 = new Stock__c();
        stk21.Provider_ID__c ='PRO-1122';
        lstStk.add(stk21);
        
        Stock__c stk11 = new Stock__c();
        stk11.Name = 'test123';
        stk11.Buyer_ID__c = 'BUY-5566';
        stk11.Payment_Branch_Number__c = '2123';
        lstStk.add(stk11);
        Insert lstStk;
        
        
        
        List<Account> lstAcc = new List<Account>();
        Account acc1 = new Account();
        acc1.Name= 'test1';
        acc1.BI_ID__c ='BUY-5566';
        
        lstAcc.add(acc1);
        
        
        Account acc2 = new Account();
        acc2.Name= 'test2';
        acc2.BI_ID__c ='PRO-1122';
        lstAcc.add(acc2);
        
        Insert lstAcc;
        
        
        
        StockAccountAssociationBatch   teststock = new StockAccountAssociationBatch  ();
        database.executebatch(teststock);
        
    }
}