force-app/main/default/objects/Account/fields/BI_ID__c.field-meta.xml
<CustomField>
    <fullName>BI_ID__c</fullName>
    <description>This is placeholder for a BI related ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is placeholder for a BI related ID.</inlineHelpText>
    <label>BI ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storage Location</fullName>
            </value>
            <value>
                <fullName>Storage Location Mailing Contact</fullName>
            </value>
            <value>
                <fullName>Adjuster</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <label>Broker</label>
</RecordType>

force-app/main/default/classes/ContactAccountRelationCreationBatch.cls
global without sharing Class ContactAccountRelationCreationBatch implements Database.Batchable<Sobject>,Database.Stateful{
	List<AccountContactRelation> lstAccConRel = new List<AccountContactRelation>();
    global Database.QueryLocator start( Database.BatchableContext BC){
        String Query = System.Label.queryContactConAccRelaCreation;
        return Database.getQueryLocator(Query);
    }
    global void execute(Database.BatchableContext BC, List<Contact> lstContact){
        	
            set<Id> lstIdRealtedAccount = new set<Id>();
          	List<AccountContactRelation> lstAccConRel1 = new List<AccountContactRelation>();
            Map<String, Account> mapAccIdAndAccObj = new Map<String, Account>();
            for(Contact objCon:lstContact){
                lstIdRealtedAccount.add(objCon.AccountId);
            }
            List<Account> lstAcc = [SELECT Id, Name, BI_Id__c, RecordTypeId, RecordType.Name 
                                    FROM Account 
                                    WHERE Id IN: lstIdRealtedAccount];
            for(Account objAcc :lstAcc){
                mapAccIdAndAccObj.put(objAcc.Id,objAcc);
            }
          
        	lstAccConRel = [SELECT AccountId, BI_Id__c, ContactId, Id, Type__c 
                            FROM AccountContactRelation 
                            WHERE AccountId IN:lstIdRealtedAccount];
        	system.debug('Size '+lstAccConRel.size());
            for(AccountContactRelation objConR : lstAccConRel){              
                Account objAccMap =  mapAccIdAndAccObj.get(objConR.AccountId);
                system.debug('Account BI Id '+objAccMap);
                if(objAccMap.RecordType.Name == 'Broker Account'){
                    objConR.Type__c = 'Broker';
                }else if(objAccMap.RecordType.Name == 'Buyer Account'){
                    objConR.Type__c = 'Buyer';
                }else if(objAccMap.RecordType.Name == 'Provider Account'){
                    objConR.Type__c = 'Provider';
                }
                objConR.BI_Id__c = objAccMap.BI_Id__c;
                lstAccConRel1.add(objConR);
                system.debug('lstAccConRel12 -'+objConR);
                system.debug('lstAccConRel-'+lstAccConRel1.size());
            }
    
          update lstAccConRel1;
    }
    global void finish(Database.BatchableContext BC){
         //update lstAccConRel;
    }
}