force-app/main/default/objects/Account/fields/BI_ID__c.field-meta.xml
<CustomField>
    <fullName>BI_ID__c</fullName>
    <description>This is placeholder for a BI related ID.</description>
    <externalId>true</externalId>
    <inlineHelpText>This is placeholder for a BI related ID.</inlineHelpText>
    <label>BI ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Buyer_ID__c.field-meta.xml
<CustomField>
    <fullName>Buyer_ID__c</fullName>
    <description>Buyer&apos;s ASAP ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Buyer&apos;s ASAP ID</inlineHelpText>
    <label>Buyer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>Provider_ID__c</fullName>
    <description>Provider&apos;s ASAP ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Provider&apos;s ASAP ID</inlineHelpText>
    <label>Provider ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StockBuyerIdProviderIdCorrectionTest.cls
@isTest
public class StockBuyerIdProviderIdCorrectionTest{

    static testMethod void testMethod1(){
        List<Stock__c> lstStk = new List<Stock__c>();
        
        Stock__c stk1 = new Stock__c();
        stk1.Buyer_ID__c = '5566';    
        lstStk.add(stk1);
     
        Stock__c stk2 = new Stock__c();
        stk2.Provider_ID__c ='1122';
        lstStk.add(stk2);

        Insert lstStk;
        

        StockBuyerIdProviderIdCorrectionBatch  teststock = new StockBuyerIdProviderIdCorrectionBatch ();
        database.executebatch(teststock);

    }
    
    static testMethod void testMethod2(){
        List<Stock__c> lstStk = new List<Stock__c>();
        
        Stock__c stk1 = new Stock__c();
        stk1.Buyer_ID__c = 'BUY-5566';    
        lstStk.add(stk1);
     
        Stock__c stk2 = new Stock__c();
        stk2.Provider_ID__c ='PRO-1122';
        lstStk.add(stk2);

        Insert lstStk;
        
        List<Account> lstAcc = new List<Account>();
        Account acc1 = new Account();
        acc1.Name= 'test1';
        acc1.BI_ID__c ='BUY-5566';
        
        lstAcc.add(acc1);
        
        
        Account acc2 = new Account();
        acc2.Name= 'test2';
        acc2.BI_ID__c ='PRO-1122';
        lstAcc.add(acc2);
        
        Insert lstAcc;
        
        

        StockAccountAssociationBatch   teststock = new StockAccountAssociationBatch  ();
        database.executebatch(teststock);

    }
}