force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Branch object</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Number__c</fullName>
    <description>Branch Number</description>
    <externalId>true</externalId>
    <label>Branch Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Primary Phone number for the Branch location</description>
    <inlineHelpText>Primary Phone number for the Branch location</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Branch_number__c.field-meta.xml
<CustomField>
    <fullName>Branch_number__c</fullName>
    <description>Admin Branch Number</description>
    <inlineHelpText>Admin Branch Number</inlineHelpText>
    <label>Branch number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Payment_Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Branch_Number__c</fullName>
    <description>User Story 500528: Stock/Stock Bid Fields for Lookup Association</description>
    <label>Payment Branch Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StockBranchNameUpdate_Test.cls
@isTest
private class StockBranchNameUpdate_Test  {
    @isTest static void StockBranchNameUpdateTest1(){  
        Id propectAccountRecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect Account').getRecordTypeId();
        Id karBSAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('KAR BS Account').getRecordTypeId();
         
        Stock__c objStock = new Stock__c(Name = '9910273',Payment_Branch_Number__c = '12341234', Branch_number__c= '12341234');
        insert objStock;
        Stock__c objStock1 = new Stock__c(Name = '2739910',Payment_Branch_Number__c = '1224', Branch_number__c= '12341234');
        insert objStock1;
        Stock__c objStock2 = new Stock__c(Name = '1099732',Payment_Branch_Number__c = '12341234', Branch_number__c= '1223');
        insert objStock2;
        
        Branch__c objBranch = new Branch__c(Name = 'Test Branch1',Phone__c='1230123011',
                                            Branch_Number__c ='12341234');
        Branch__c objBranch1 = new Branch__c(Name = 'Test Branch12',Phone__c='1239012341',
                                            Branch_Number__c ='1223');
        Branch__c objBranch2 = new Branch__c(Name = 'Test Branch12',Phone__c='1239012344',
                                            Branch_Number__c ='1224');
        insert objBranch;
        
        Test.startTest();
        StockBranchNameUpdate objStoBraNameUpd = new StockBranchNameUpdate();
        database.executeBatch(objStoBraNameUpd);
        Test.stopTest();
    }
}