force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Branch object</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch_Manager__c.field-meta.xml
<CustomField>
    <fullName>Branch_Manager__c</fullName>
    <description>Formula field related to Manager on Branch object lookup</description>
    <inlineHelpText>Formula field related to Manager on Branch object lookup</inlineHelpText>
    <label>Branch Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Manager__c.field-meta.xml
<CustomField>
    <fullName>Branch_Manager__c</fullName>
    <description>Branch Manager Name</description>
    <inlineHelpText>Branch Manager Name</inlineHelpText>
    <label>Branch Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Agent_Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Agent_Reviewed__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Reviewed</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Buyer_Feedback</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/medallia_xm__Medallia_Feedback_id__c.field-meta.xml
<CustomField>
    <fullName>medallia_xm__Medallia_Feedback_id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link Case to a specific piece of feedback stored in the custom Medallia feedback object</description>
    <label>Medallia - Feedback id</label>
    <referenceTo>medallia_xm__Medallia_Feedback__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Originating_Case__c.field-meta.xml
<CustomField>
    <fullName>Originating_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Originating Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Buyer FeedBack</relationshipLabel>
    <relationshipName>Survey_Feedback_case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reason_for_Case__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Case__c</fullName>
    <label>Reason for Case</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Inquiry</fullName>
                <isActive>false</isActive>
                <label>3rd Party Inquiry</label>
            </value>
            <value>
                <fullName>Account Credit</fullName>
            </value>
            <value>
                <fullName>Account Renewal</fullName>
                <isActive>false</isActive>
                <label>Account Renewal</label>
            </value>
            <value>
                <fullName>Account Review</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>AC Credential Request</fullName>
            </value>
            <value>
                <fullName>Add/Remove Bidders</fullName>
            </value>
            <value>
                <fullName>Adjustments</fullName>
                <isActive>false</isActive>
                <label>Adjustments</label>
            </value>
            <value>
                <fullName>All Other Documents</fullName>
            </value>
            <value>
                <fullName>Archived Stock</fullName>
            </value>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Assignment Verification</fullName>
            </value>
            <value>
                <fullName>Assistance No Longer required</fullName>
            </value>
            <value>
                <fullName>Auction Center - Desktop</fullName>
                <isActive>false</isActive>
                <label>Auction Center - Desktop</label>
            </value>
            <value>
                <fullName>AuctionNow</fullName>
            </value>
            <value>
                <fullName>Auction Rules</fullName>
            </value>
            <value>
                <fullName>Average Salvage Value</fullName>
            </value>
            <value>
                <fullName>Bad Connection</fullName>
            </value>
            <value>
                <fullName>BBB Complaints</fullName>
            </value>
            <value>
                <fullName>Bid Dispute</fullName>
            </value>
            <value>
                <fullName>Bid Log Request</fullName>
            </value>
            <value>
                <fullName>Blank Voicemail</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Branch Connectivity</fullName>
                <isActive>false</isActive>
                <label>Branch Connectivity</label>
            </value>
            <value>
                <fullName>Branch Information - Do Not Use</fullName>
                <isActive>false</isActive>
                <label>Branch Information - Do Not Use</label>
            </value>
            <value>
                <fullName>Branch Title Inquiry</fullName>
                <isActive>false</isActive>
                <label>Branch Title Inquiry</label>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Buyer Credit card</fullName>
                <isActive>false</isActive>
                <label>Buyer Credit card</label>
            </value>
            <value>
                <fullName>Buyer Feedback</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>License Inquiry</fullName>
            </value>
            <value>
                <fullName>License Update</fullName>
            </value>
            <value>
                <fullName>New Account</fullName>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>Upgrade/Downgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Response</label>
    <referenceTo>medallia_xm__Medallia_Feedback__c</referenceTo>
    <relationshipLabel>Cases (Response)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch_Manager__c.field-meta.xml
<CustomField>
    <fullName>Branch_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Branch Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/CaseTriggerHandler.cls
public class CaseTriggerHandler extends TriggerHandler {
    private static String BUYER_FEEDBACK_RT ='Buyer Feedback' ;
    private static String BUYER_SERVICES_RT ='Buyer Services' ;
    private static String CASE_OBJ ='Case' ;
    private static Map<Id,Case> triggerOldMap;
    private static Map<Id,Case> triggerNewMap;
    private static List<Case> triggerNew;
    private static List<Case> triggerOld;
    private static map<String, Id> mapOfProfileNameAndId = new map<String, Id>();
    private static String ErrorMessage = System.Label.ErrorMessageCloseCase;
    private static String ErrorMessageAllTask = System.Label.CaseAllTaskNotCloseError;
    private static User medalliaIntegrationUser = new User();
    
    protected override void setup(){
        triggerOldMap = (Trigger.oldMap != null ? (Map<Id,Case>) Trigger.oldMap : null );
        triggerNewMap = (Trigger.newMap != null ? (Map<Id,Case>) Trigger.newMap : null );
        triggerOld  = (Trigger.old != null ? (List<Case>) Trigger.old : null );
        triggerNew = (Trigger.new != null ? (List<Case>) Trigger.new : null );
        medalliaIntegrationUser = [SELECT Id,Name FROM User WHERE Name = 'Medallia Integration User'];
    }
    
    protected override void doBefore(){        
        if(Trigger.isInsert){
            madalliaSurveyCaseCreation();
        }else if (Trigger.isUpdate) {
            caseUpdateBranchManagerEmailEscalation();
            closedCaseCantUpdated();
            caseAllTaskCompletedBeforeClosed();
        }
    }
    
    protected override void doAfter(){
        if (Trigger.isInsert){
        }else if (Trigger.isUpdate) 
        {
            for(Case caseRecords : triggernew){}
        } //endof if(Trigger.isUpdate)
    }
    
    private void madalliaSurveyCaseCreation(){
        system.debug('yeah');
        List<String> lstCase = new List<String>();
        Map<Id, Case> mapOfcaseIdAndCase = new Map<Id, Case>();
        
        for(Case caseRecords : triggernew){
            system.debug('forcaseRecords '+caseRecords);
            system.debug('Medallia user '+caseRecords.CreatedById);
            system.debug('Medallia user1 '+(caseRecords <> Null));
            system.debug('Medallia user2 '+(caseRecords.OwnerId <> null && caseRecords.OwnerId == medalliaIntegrationUser.Id));
            system.debug('Medallia user3 '+(caseRecords.RecordTypeId <> Null && caseRecords.RecordTypeId == getCaseRecordTypeIdbyName(BUYER_FEEDBACK_RT)));
            if(caseRecords <> Null){
                if(caseRecords.RecordTypeId <> Null && caseRecords.RecordTypeId == getCaseRecordTypeIdbyName(BUYER_FEEDBACK_RT)||
                   ((caseRecords.OwnerId <> null && caseRecords.OwnerId == medalliaIntegrationUser.Id)|| caseRecords.medallia_xm__Medallia_Feedback_id__c <> null)){
                       if(caseRecords.Originating_Case__c <> Null){
                           lstCase.add(caseRecords.Originating_Case__c);
                       } else if(caseRecords.ParentId <> Null){
                           caseRecords.Originating_Case__c = caseRecords.ParentId;
                           lstCase.add(caseRecords.Originating_Case__c);
                       }else{
                           caseRecords.addError('ParentId or Originating Case is required field for Buyer Feedback Case');
                       }
                   }
            }
        }
        system.debug(lstCase);
        List<String> lstOfOrginalCaseId = new List<String>();
        for(Case objCaseRec : [SELECT Id, Description, OwnerId FROM Case WHERE Id IN: lstCase ]){
            mapOfcaseIdAndCase.put(objCaseRec.Id, objCaseRec);
            lstOfOrginalCaseId.add(objCaseRec.Id);
        }
        map<Id, medallia_xm__Medallia_Feedback__c> mapOfCaseIdFeddback = new map<Id, medallia_xm__Medallia_Feedback__c>();
        for(medallia_xm__Medallia_Feedback__c objResponse: [SELECT medallia_xm__Original_case_Number__c, Id, Name, medallia_xm__Original_case_Owner_id__c 
                                                            FROM medallia_xm__Medallia_Feedback__c
                                                            WHERE medallia_xm__Original_case_Number__c IN: lstOfOrginalCaseId]){
                                                                system.debug('objResponse--  '+objResponse);
                                                                mapOfCaseIdFeddback.put(objResponse.medallia_xm__Original_case_Number__c, objResponse);
                                                            }
        for(Case caseRecords : triggernew){
            system.debug(mapOfCaseIdFeddback);
            if(caseRecords.RecordTypeId == getCaseRecordTypeIdbyName(BUYER_FEEDBACK_RT) && mapOfcaseIdAndCase.get(caseRecords.Originating_Case__c)<> null){
                caseRecords.Agent_Reviewed__c = mapOfcaseIdAndCase.get(caseRecords.Originating_Case__c).OwnerId;
                caseRecords.Description = mapOfcaseIdAndCase.get(caseRecords.Originating_Case__c).Description;
                caseRecords.Response__c = mapOfCaseIdFeddback.get(caseRecords.Originating_Case__c) <> null ? mapOfCaseIdFeddback.get(caseRecords.Originating_Case__c).Id : null;
                system.debug('caseRecords.Response__c ' +caseRecords.Response__c);
            }
        }
    }
    private Id getCaseRecordTypeIdbyName(String strRecordTypeName)
    {
        Schema.DescribeSObjectResult  cs = Schema.getGlobalDescribe().get(CASE_OBJ).getDescribe();
        RecordTypeInfo rt = cs.getRecordTypeInfosByName().get(strRecordTypeName);
        Id recId;
        if(rt != null){
            recId = cs.getRecordTypeInfosByName().get(strRecordTypeName).getRecordTypeId();
        }
        return recId;
    }
    @TestVisible
    private static String getRecordTypeNameById(String CASE_OBJ, Id strRecordTypeId)
    {
        return Schema.getGlobalDescribe().get(CASE_OBJ).getDescribe().getRecordTypeInfosById().get(strRecordTypeId).getName();
    } 
    private void closedCaseCantUpdated(){
        
        for(case recCase:triggerNew){
            case oldCase = triggerOldMap.get(recCase.Id);
            if(oldCase.Status == 'Closed' && recCase.Status <> 'Re-Opened' ) {
                recCase.addError(ErrorMessage);
            }
        }
    }
    /********************************************************************
    * @User Storys: 541503												*
    * @Method Name: caseUpdateBranchManagerEmailEscalation				*
    * @Param: void														*
    * @Return Type:void													*
    * @Description: 													*
    * *******************************************************************/
    private void caseUpdateBranchManagerEmailEscalation(){
        Id caseRTId = getCaseRecordTypeIdbyName('Remote Workforce');
        Set<Id> relatedBranchIds = new Set<Id>();
        Map<Id,Id> mapOfBranchAndBranchManager = new Map<Id,Id>();
        //adding all CaseBranchId in set
        for(case recCase:triggerNew){
            case oldCase = triggerOldMap.get(recCase.Id);
            if(oldCase.IsEscalated  <> true && recCase.IsEscalated  == true && recCase.RecordTypeId == caseRTId){
                if(recCase.Branch__c <> null){
                    relatedBranchIds.add(recCase.Branch__c);
                }else{
                    recCase.addError('Case can not be escalated until branch is not associated');
                }
            }
            
        }
        //query on contact for find all Branch Manager and making map for Branch and Branch Manager
        if(!relatedBranchIds.isEmpty() ){
            /*for(Contact objContact:[SELECT Id, Name, Branch__c, Branch_Manager__c FROM Contact WHERE Branch__c IN: relatedBranchIds AND Branch_Manager__c = true]){
                mapOfBranchAndBranchManager.put(objContact.Branch__c, objContact.Id);
                
                }*/
            // if(!mapOfBranchAndBranchManager.isEmpty()){
            Group queueOCC = [SELECT Id, Name, DeveloperName, Email, Type FROM Group where Type='Queue' And Name ='Oklahoma City case' limit 1];
            system.debug('queueOCC '+queueOCC);
            for(case recCase:triggerNew){
                system.debug(recCase.RecordTypeId+'--'+caseRTId);
                case oldCase = triggerOldMap.get(recCase.Id);
                if(oldCase.IsEscalated  <> true && recCase.IsEscalated  == true  && recCase.RecordTypeId == caseRTId && queueOCC <> null) {
                    recCase.OwnerId = queueOCC.Id;
                }
                // }
            }            
        }        
    }
    /********************************************************************
    * @User Storys: 666399 Registration Task Completion Validation rule	*
    * @Method Name: caseAllTaskCompletedBeforeClosed					*
    * @Param: Void														*
    * @Return Type:void													*												
    * @Description: Buyer service can only be if all task is completed	* 
    * @Date: 19 May 2021												*
    * ******************************************************************/
    private void caseAllTaskCompletedBeforeClosed(){
        List<String> lstCaseId = new List<String>();
        Boolean isAllTaskIsClosed = true;
        Map<String,List<Task>> MapOfCaseTask = new Map<String,List<Task>>();
        Id caseBuyerServicesRTId = getCaseRecordTypeIdbyName(BUYER_SERVICES_RT);
        
        for(case recCase:triggerNew){
            if (recCase.recordTypeId == caseBuyerServicesRTId){
                lstCaseId.add(recCase.Id);
            }
        }
        for(Task objTask :[SELECT Id,IsClosed,WhatId FROM Task WHERE WhatId IN :lstCaseId]){
            if(MapOfCaseTask.containsKey(objTask.WhatId)){
                List<Task> lstOfTask = MapOfCaseTask.get(objTask.WhatId);
                lstOfTask.add(objTask);
                MapOfCaseTask.put(objTask.WhatId,lstOfTask );
            }else{
                List<Task> listOfTask = new List<Task>();
                listOfTask.add(objTask);
                MapOfCaseTask.put(objTask.WhatId,listOfTask);
            }
        }
        for(case recCase:triggerNew){
            case oldCase = triggerOldMap.get(recCase.Id);        
            if((oldCase.status <> 'Closed' && recCase.status == 'Closed') 
               && (recCase.Reason_for_Case__c == 'New Account' || recCase.Reason_for_Case__c == 'Account Update' 
                   || recCase.Reason_for_Case__c == 'License Update' || recCase.Reason_for_Case__c == 'Account Renewal'
                   || recCase.Reason_for_Case__c == 'Upgrade/Downgrade'|| recCase.Reason_for_Case__c == 'License Inquiry'
                   || recCase.Reason_for_Case__c == ' All Other Documents')  && recCase.Type == 'Registration'){
                list<Task> allTaskToCase = MapOfCaseTask.get(recCase.Id);
                if(allTaskToCase <> null && allTaskToCase.isEmpty() == false){
                    for(Task objTask:allTaskToCase){
                        if(objTask.isClosed == false){
                            isAllTaskIsClosed = false;
                        }                
                    }
                }
                if(isAllTaskIsClosed == false){
                    if(!Test.isRunningTest()){
                         recCase.addError(ErrorMessageAllTask);
                    }else{
                        system.debug(ErrorMessageAllTask);
                    }                   
                }          
            }
        }      
    }	
}