force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Branch object</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CRC_checksum__c.field-meta.xml
<CustomField>
    <fullName>CRC_checksum__c</fullName>
    <label>Checksum</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CRC_Provider_SLA__c.field-meta.xml
<CustomField>
    <fullName>CRC_Provider_SLA__c</fullName>
    <label>Provider SLA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Hour</fullName>
            </value>
            <value>
                <fullName>2 Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>The field displays the buyer&apos;s Auction Center password and is used only by the Buyer Service&apos;s team.</description>
    <inlineHelpText>The field displays the buyer&apos;s Auction Center password and is used only by the Buyer Service&apos;s team.</inlineHelpText>
    <label>Password</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Adjuster__c.field-meta.xml
<CustomField>
    <fullName>CRC_Adjuster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjuster</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>ReleaseAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Branch_Manager__c.field-meta.xml
<CustomField>
    <fullName>CRC_Branch_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases (Branch Manager)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Charges_Cleared__c.field-meta.xml
<CustomField>
    <fullName>CRC_Charges_Cleared__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Charges Cleared</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Checksum__c.field-meta.xml
<CustomField>
    <fullName>CRC_Checksum__c</fullName>
    <label>Checksum</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Claim__c.field-meta.xml
<CustomField>
    <fullName>CRC_Claim__c</fullName>
    <label>Claim #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Date_of_Loss__c.field-meta.xml
<CustomField>
    <fullName>CRC_Date_of_Loss__c</fullName>
    <label>Date of Loss</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Pickup_Location_Type__c.field-meta.xml
<CustomField>
    <fullName>CRC_Pickup_Location_Type__c</fullName>
    <label>Pickup Location Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RESIDENTIAL</fullName>
            </value>
            <value>
                <fullName>BUSINESS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Policy__c.field-meta.xml
<CustomField>
    <fullName>CRC_Policy__c</fullName>
    <label>Policy #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Provider_SLA__c.field-meta.xml
<CustomField>
    <fullName>CRC_Provider_SLA__c</fullName>
    <label>Provider SLA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 Hour</fullName>
            </value>
            <value>
                <fullName>2 Hour</fullName>
            </value>
            <value>
                <fullName>Same Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Release_Problem_Email__c.field-meta.xml
<CustomField>
    <fullName>CRC_Release_Problem_Email__c</fullName>
    <label>Release Problem Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Salvage_Id__c.field-meta.xml
<CustomField>
    <fullName>CRC_Salvage_Id__c</fullName>
    <label>Salvage Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Stock_Number__c.field-meta.xml
<CustomField>
    <fullName>CRC_Stock_Number__c</fullName>
    <label>Stock Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_City__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_City__c</fullName>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Email__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Fax__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Fax__c</fullName>
    <label>Fax</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_First_Name__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_First_Name__c</fullName>
    <label>First Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Primary_Extension__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Primary_Extension__c</fullName>
    <label>Primary Extension</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Primary_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Primary_Phone_Number__c</fullName>
    <label>Primary Phone Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Primary_Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Primary_Phone_Type__c</fullName>
    <label>Primary Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPNT</fullName>
                <label>Cell Phone</label>
            </value>
            <value>
                <fullName>CPWT</fullName>
                <label>Cell Phone with Text</label>
            </value>
            <value>
                <fullName>HMPN</fullName>
                <label>Home Phone</label>
            </value>
            <value>
                <fullName>WKPN</fullName>
                <label>Work Phone</label>
            </value>
            <value>
                <fullName>1</fullName>
                <isActive>false</isActive>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
                <isActive>false</isActive>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
                <isActive>false</isActive>
                <label>3</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Secondary_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Secondary_Phone_Number__c</fullName>
    <label>Secondary Phone Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Secondary_Phone_Type__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Secondary_Phone_Type__c</fullName>
    <label>Secondary Phone Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>CPNT</fullName>
            </value>
            <value>
                <fullName>CPWT</fullName>
            </value>
            <value>
                <fullName>HMPN</fullName>
            </value>
            <value>
                <fullName>WKPN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_VO_Zip__c.field-meta.xml
<CustomField>
    <fullName>CRC_VO_Zip__c</fullName>
    <label>Zip</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock</label>
    <referenceTo>Stock__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Console_Tab__e/Console_Tab__e.object-meta.xml
<CustomObject>
    <label>Console Tab</label>
    <pluralLabel>Console Tabs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Console_Tab__e/fields/Refresh_Successful__c.field-meta.xml
<CustomField>
    <fullName>Refresh_Successful__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Refresh Successful</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Storage Location</fullName>
            </value>
            <value>
                <fullName>Storage Location Mailing Contact</fullName>
            </value>
            <value>
                <fullName>Adjuster</fullName>
            </value>
            <value>
                <fullName>Branch Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <label>Public</label>
</RecordType>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRC_ReleaseAssignmentController.cls
public without sharing class CRC_ReleaseAssignmentController {
 
  
    @AuraEnabled
    public static void checkInCheckOutMethod(String recId, String operation){
        
        if(operation == 'checkOut')
        {
            CRC_Constants.REFRESH_AND_CHECKOUT = true;
            try{
                RPM_APIController.refreshFromRPM(recId); 
                Database.executeBatch(new CRC_Priority_Update()); 
            }catch(Exception e){
                throw new AuraHandledException(e.getMessage());
            }
            
        }else if(operation == 'checkIn')
        {
            String queueid = CRC_Constants.CRC_PRIORITY_ASSIGNMENTS;
            Case c = new case();
            c.id = recId;
            c.ownerid = queueid;
            try{
                Database.update(c);
                EventBus.publish(new Console_Tab__e(Refresh_Successful__c=true)); //Added by Anuj on 25th Nov, 21 as part of testing
                Database.executeBatch(new CRC_Priority_Update());
            }catch(Exception e){ 
                throw new AuraHandledException(e.getMessage());
            }
           
        }
    }

    @AuraEnabled
    public static string releaseVehicleCheck(String recId){
        
       Case objCase = [Select Id,Status from Case where id =: recId];

       if(objCase.status == 'Release Problem'){
            throw new AuraHandledException('You cannot release the vehicle as there are open release problems associated with it'); 
       }
       if(objCase.status == 'Wait Dispatch'){
            throw new AuraHandledException('This vehicle has already been released. You cannot re-release the vehicle');
       }

        return 'Success';
    }

    @AuraEnabled
    public static Map<String,Object> releaseVehicle(String recId,Map<String,object> request){
  
          Case objCase = [Select Id,Stock__r.Name,CRC_Salvage_Id__c,CRC_Charges_Cleared__c,CRC_Checksum__c from Case where id =: recId];
                if(objCase != null){
                    request.put('IAAI_STOCK_NUMBER',objCase.Stock__r.Name);
                    request.put('SALVAGE_ID',objCase.CRC_Salvage_Id__c);
                    request.put('CHECKSUM',objCase.CRC_Checksum__c);
                    request.put('VR_CHARGES_CLEARED',objCase.CRC_Charges_Cleared__c);
                    request.put('Id',recId);
                }
                if(request.get('VR_NOTE_DESCRIPTION') != null){
                    request.put('CRC_Note_Category__c','DSP');
                    request.put('Description',request.get('VR_NOTE_DESCRIPTION'));
                }


            try {
                Map<String, Object> response = new Map<String, Object>();
                RPM_ReleaseAssignmentController.BasicHttpBinding_IAssignment obj = new RPM_ReleaseAssignmentController.BasicHttpBinding_IAssignment();
                Blob headerValue = Blob.valueOf(CRC_Constants.RPM_CREDENTIALS.DeveloperName + ':' + CRC_Constants.RPM_CREDENTIALS.Password__c);
                String authorizationHeader = 'BASIC '+ EncodingUtil.base64Encode(headerValue);
                Map<String,String> inputHeaderMap = new  Map<String,String>();
                inputHeaderMap.put('Authorization', authorizationHeader);
                obj.inputHttpHeaders_x = inputHeaderMap;
                obj.timeout_x = Integer.valueOf(CRC_Constants.RPM_CREDENTIALS.Callout_Time_Limit__c);
                String soapResponse = obj.IAAI_ASSIGNMENT_INFO(CRC_RPM_RequestHelper.releaseVehiclePost(request), CRC_Constants.RPM_CREDENTIALS.DeveloperName);
                System.debug(soapResponse);
                //response = response.put('response', soapResponse);
                response = CRC_RPM_RequestHelper.parseRPMResponse(soapResponse);
                    if(response.get('STATUS_CODE') == 'ACCEPT'){
                        Map<String, Object> result = RPM_APIController.RPM_AddUserNotes(request);
                    }
                RPM_APIController.createLog('Saleforce', 'RPM', 'manageReleaseProblem',  'request', soapResponse, 'http://uat.eai.iaai.com/IAAI.Services/Assignment.svc', 'Success');
                
                return response;

            } catch (Exception e) {
                System.debug(e.getMessage()+'---'+e.getStackTraceString());
                throw new AuraHandledException(e.getMessage());
            }
        

    }
    
   

    @AuraEnabled
    public static Map<String, Object> getCaseContactData(String rAId){
        try { 
            Case cs = [Select Id,CRC_Claim__c,CRC_Policy__c,CRC_Date_of_Loss__c,CRC_Provider_SLA__c,
                        Branch__c,Branch__r.Name,CRC_Branch_Manager__r.Name,OwnerId, Owner.Name,Owner.Email, CRC_VO_First_Name__c, CRC_VO_Last_Name__c,
                        CRC_VO_Email__c, CRC_VO_Primary_Phone_Number__c, CRC_VO_Primary_Phone_Type__c, CRC_VO_Secondary_Phone_Number__c, 
                        CRC_VO_Secondary_Phone_Type__c, CRC_VO_Address_Line_1__c, CRC_VO_Fax__c, 
                        CRC_VO_Zip__c, CRC_VO_City__c, CRC_VO_Primary_Extension__c, CRC_Salvage_Id__c, CRC_Checksum__c,
                        Stock__r.Stock__c, Account.Name , CRC_Branch_Manager__r.FirstName, CRC_Branch_Manager__r.LastName, 
                        CRC_Branch_Manager__r.RecordType.Name, CRC_Branch_Manager__r.Email, CRC_Branch_Manager__r.Fax, CRC_Branch_Manager__r.Type__c, 
                        CRC_Branch_Manager__r.Phone, CRC_Release_Problem_Email__c, CRC_Branch_Manager__r.OtherPhone, 
                        CRC_Branch_Manager__r.MailingStreet, CRC_Branch_Manager__r.MailingCity, CRC_Branch_Manager__r.MailingState, 
                        CRC_Branch_Manager__r.MailingPostalCode, CRC_Branch_Manager__r.MailingCountry, CRC_Pickup_Location_Type__c, 
                        CRC_Adjuster__c, CRC_Adjuster__r.Name, CRC_Adjuster__r.FirstName, CRC_Adjuster__r.LastName, CRC_Adjuster__r.Email, 
                        CRC_Adjuster__r.Fax, CRC_Adjuster__r.Phone, CRC_Adjuster__r.OtherPhone, CRC_Adjuster__r.MailingStreet, CRC_Stock_Number__c,
                        CRC_Adjuster__r.MailingCity, CRC_Adjuster__r.MailingState, CRC_Adjuster__r.MailingPostalCode, CRC_Adjuster__r.MailingCountry    
                        FROM Case 
                        WHERE Id =: RAId Limit 1];
            return new Map<String, Object> {
                'case'          =>  cs,
                'branchManager' =>  (String.isNotBlank(cs.CRC_Branch_Manager__c) ? cs.CRC_Branch_Manager__r : null),
                'adjuster'  =>  cs.CRC_Adjuster__r
            };
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


 
}