force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Branch object</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Branch_Manager__c.field-meta.xml
<CustomField>
    <fullName>Branch_Manager__c</fullName>
    <description>Formula field related to Manager on Branch object lookup</description>
    <inlineHelpText>Formula field related to Manager on Branch object lookup</inlineHelpText>
    <label>Branch Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Manager__c.field-meta.xml
<CustomField>
    <fullName>Branch_Manager__c</fullName>
    <description>Branch Manager Name</description>
    <inlineHelpText>Branch Manager Name</inlineHelpText>
    <label>Branch Manager</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Branch Name</description>
    <label>Branch Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Number__c</fullName>
    <description>Branch Number</description>
    <externalId>true</externalId>
    <label>Branch Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Primary Phone number for the Branch location</description>
    <inlineHelpText>Primary Phone number for the Branch location</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Originating_Case__c.field-meta.xml
<CustomField>
    <fullName>Originating_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Originating Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Buyer FeedBack</relationshipLabel>
    <relationshipName>Survey_Feedback_case</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reason_for_Case__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Case__c</fullName>
    <label>Reason for Case</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party Inquiry</fullName>
                <isActive>false</isActive>
                <label>3rd Party Inquiry</label>
            </value>
            <value>
                <fullName>Account Credit</fullName>
            </value>
            <value>
                <fullName>Account Renewal</fullName>
                <isActive>false</isActive>
                <label>Account Renewal</label>
            </value>
            <value>
                <fullName>Account Review</fullName>
            </value>
            <value>
                <fullName>Account Update</fullName>
            </value>
            <value>
                <fullName>AC Credential Request</fullName>
            </value>
            <value>
                <fullName>Add/Remove Bidders</fullName>
            </value>
            <value>
                <fullName>Adjustments</fullName>
                <isActive>false</isActive>
                <label>Adjustments</label>
            </value>
            <value>
                <fullName>All Other Documents</fullName>
            </value>
            <value>
                <fullName>Archived Stock</fullName>
            </value>
            <value>
                <fullName>Assignment</fullName>
            </value>
            <value>
                <fullName>Assignment Verification</fullName>
            </value>
            <value>
                <fullName>Assistance No Longer required</fullName>
            </value>
            <value>
                <fullName>Auction Center - Desktop</fullName>
                <isActive>false</isActive>
                <label>Auction Center - Desktop</label>
            </value>
            <value>
                <fullName>AuctionNow</fullName>
            </value>
            <value>
                <fullName>Auction Rules</fullName>
            </value>
            <value>
                <fullName>Average Salvage Value</fullName>
            </value>
            <value>
                <fullName>Bad Connection</fullName>
            </value>
            <value>
                <fullName>BBB Complaints</fullName>
            </value>
            <value>
                <fullName>Bid Dispute</fullName>
            </value>
            <value>
                <fullName>Bid Log Request</fullName>
            </value>
            <value>
                <fullName>Blank Voicemail</fullName>
            </value>
            <value>
                <fullName>Branch</fullName>
            </value>
            <value>
                <fullName>Branch Connectivity</fullName>
                <isActive>false</isActive>
                <label>Branch Connectivity</label>
            </value>
            <value>
                <fullName>Branch Information - Do Not Use</fullName>
                <isActive>false</isActive>
                <label>Branch Information - Do Not Use</label>
            </value>
            <value>
                <fullName>Branch Title Inquiry</fullName>
                <isActive>false</isActive>
                <label>Branch Title Inquiry</label>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>Buyer Credit card</fullName>
                <isActive>false</isActive>
                <label>Buyer Credit card</label>
            </value>
            <value>
                <fullName>Buyer Feedback</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Desktop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Branch_Manager__c.field-meta.xml
<CustomField>
    <fullName>Branch_Manager__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Branch Manager</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/CaseTriggerHandler_Test.cls
@isTest
public class CaseTriggerHandler_Test {
    static testMethod void madalliaSurveyCaseCreation_Test1(){
        ID FeedbackRT_Id = Schema.getGlobalDescribe().get('CASE').getDescribe().getRecordTypeInfosByName().get('Buyer Feedback').getRecordTypeId();
        ID BuyerServicesRT_ID = Schema.getGlobalDescribe().get('CASE').getDescribe().getRecordTypeInfosByName().get('Buyer Services').getRecordTypeId();
        Case recBuyerServiceCase = new Case(Subject ='test case', RecordTypeId=BuyerServicesRT_ID, Description ='test');
        insert recBuyerServiceCase;
        Case recSurveyFeedbackCase = new case(Subject ='test case', RecordTypeId=FeedbackRT_Id, Originating_Case__c = recBuyerServiceCase.id);
        insert recSurveyFeedbackCase;
        recBuyerServiceCase.Comments = 'test';
        update recBuyerServiceCase;
        
    }
    static testMethod void caseAllTaskCompletedBeforeClosed_Test(){
        Branch__c objBranch = new Branch__c(Branch_Name__c = 'test', Branch_Number__c = '1998',phone__c='99999999');
        insert objBranch;
        contact objC = new contact(FirstName = 'Test', LastName= 'User', Branch__c = objBranch.Id, Branch_Manager__c = true);
        insert objC;
        ID BuyerAccountRT_ID = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Buyer Account').getRecordTypeId();
        Account objAcc = new Account(Name ='AccountTest', recordtypeId = BuyerAccountRT_ID);
        insert objAcc;
        Contact objContact = new Contact(firstName ='Manish', LastName ='Singh', AccountId = objAcc.Id);
        insert objContact;
        //ID FeedbackRT_Id = Schema.getGlobalDescribe().get('CASE').getDescribe().getRecordTypeInfosByName().get('Buyer Feedback').getRecordTypeId();
        ID BuyerServicesRT_ID = Schema.getGlobalDescribe().get('CASE').getDescribe().getRecordTypeInfosByName().get('Buyer Services').getRecordTypeId();
        Case recBuyerServiceCase = new Case(Subject ='test case', RecordTypeId=BuyerServicesRT_ID, IsEscalated  = false, Description ='test', 
                                            Branch__c= objBranch.id, AccountId = objAcc.Id, ContactId = objContact.Id, type = 'Auction Center Support', 
                                            Reason_for_Case__c='Desktop');
        insert recBuyerServiceCase;
        Task objTaskRec = new Task(Description='test', Subject='test Subject', status = 'Not Started', 
                                   whatId = recBuyerServiceCase.id);
        insert objTaskRec;
        Task objTaskRec1 = new Task(Description='test1', Subject='test Subject1', status = 'Not Started', 
                                   whatId = recBuyerServiceCase.id);
        insert objTaskRec1;
        recBuyerServiceCase.Status = 'closed';
        update recBuyerServiceCase;
        
    }
    static testMethod void caseUpdateBranchManagerEmailEscalation_Test(){
        Branch__c objBranch = new Branch__c(Branch_Name__c = 'test', Branch_Number__c = '1998',phone__c='99999999');
        insert objBranch;
        contact objC = new contact(FirstName = 'Test', LastName= 'User', Branch__c = objBranch.Id, Branch_Manager__c = true);
        insert objC;
        ID FeedbackRT_Id = Schema.getGlobalDescribe().get('CASE').getDescribe().getRecordTypeInfosByName().get('Buyer Feedback').getRecordTypeId();
        ID BuyerServicesRT_ID = Schema.getGlobalDescribe().get('CASE').getDescribe().getRecordTypeInfosByName().get('Buyer Services').getRecordTypeId();
        Case recBuyerServiceCase = new Case(Subject ='test case', RecordTypeId=BuyerServicesRT_ID, IsEscalated  = false, Description ='test', Branch__c= objBranch.id);
        insert recBuyerServiceCase;
        recBuyerServiceCase.IsEscalated = true;
        update recBuyerServiceCase;
        string Name = CaseTriggerHandler.getRecordTypeNameById('case', BuyerServicesRT_ID);
        Case recSurveyFeedbackCase = new case(Subject ='test case', RecordTypeId=FeedbackRT_Id, Originating_Case__c = recBuyerServiceCase.id);
        insert recSurveyFeedbackCase;
        recBuyerServiceCase.Comments = 'test';
        update recBuyerServiceCase;
        
    }
    
}