force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Branch object</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <label>FEIN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/VRD_Level__c.field-meta.xml
<CustomField>
    <fullName>VRD_Level__c</fullName>
    <label>VRD Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Level 1</fullName>
            </value>
            <value>
                <fullName>Level  2</fullName>
            </value>
            <value>
                <fullName>Level  3</fullName>
            </value>
            <value>
                <fullName>Level  5</fullName>
            </value>
            <value>
                <fullName>Level  6</fullName>
            </value>
            <value>
                <fullName>Level  7</fullName>
            </value>
            <value>
                <fullName>Level  8</fullName>
            </value>
            <value>
                <fullName>Level  9</fullName>
            </value>
            <value>
                <fullName>Level  10</fullName>
            </value>
            <value>
                <fullName>Level  11</fullName>
            </value>
            <value>
                <fullName>Level  12</fullName>
            </value>
            <value>
                <fullName>Level  13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Prospect_Account.recordType-meta.xml
<RecordType>
    <fullName>Prospect_Account</fullName>
    <active>true</active>
    <description>If you&apos;ve already searched for an account and checked that it doesn&apos;t exist, you may create a prospect.</description>
    <label>Prospect Account</label>
</RecordType>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Primary Phone number for the Branch location</description>
    <inlineHelpText>Primary Phone number for the Branch location</inlineHelpText>
    <label>Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SubmitContractAdminController_Test.cls
@isTest
private class SubmitContractAdminController_Test {
    static testMethod void getCurrentAccountTestWithNoValue(){
        RecordType objRed = [SELECT DeveloperName,Id,Name FROM RecordType WHERE DeveloperName = 'Prospect_Account'];
        Account objAccount = new Account();
        objAccount.Name = 'test Account Contract Admin';
        objAccount.RecordTypeId = objRed.Id;
        insert objAccount;
        Test.startTest();
      	SubmitContractAdminController.checkMedatoryFieldAccount reponse = SubmitContractAdminController.getCurrentAccount(objAccount.Id);
        SubmitContractAdminController.submitApprovalProcess(objAccount.Id);
        Test.stopTest();
    }
    static testMethod void getCurrentAccountTestWithSomeValueFEIN(){
        Account objAccount = new Account();
        objAccount.Name = 'test Account Contract Admin';
        objAccount.FEIN__c = '123456';
        insert objAccount;
        Test.startTest();
      	SubmitContractAdminController.checkMedatoryFieldAccount reponse = SubmitContractAdminController.getCurrentAccount(objAccount.Id);
        //SubmitContractAdminController.submitApprovalProcess(objAccount.Id);
        Test.stopTest();
    }
     static testMethod void getCurrentAccountTestWithSomeValue(){
         RecordType objRed = [SELECT DeveloperName,Id,Name FROM RecordType WHERE DeveloperName = 'Prospect_Account'];
        Account objAccount = new Account();
        objAccount.Name = 'test Account Contract Admin';
         objAccount.RecordTypeId = objRed.Id;
        objAccount.FEIN__c = '123456';
         //objAccount.VRD_Level__c = 'Level 2';
        insert objAccount;
        Test.startTest();
      	SubmitContractAdminController.checkMedatoryFieldAccount reponse = SubmitContractAdminController.getCurrentAccount(objAccount.Id);
        SubmitContractAdminController.submitApprovalProcess(objAccount.Id);
        Test.stopTest();
         
         
    }
     static testMethod void getCurrentAccountTestWithSomeValue01(){
         RecordType objRed = [SELECT DeveloperName,Id,Name FROM RecordType WHERE DeveloperName = 'Prospect_Account'];
        Account testAccount = new Account();
        testAccount.Name='Test Account' ;
         testAccount.RecordTypeId = objRed.Id;
        insert testAccount;    
         
     	ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true,
         	Document_Type__c = 'W-9'
         	//ContentDocumentId = documents[0].Id
        );
         
        insert contentVersion; 
         
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
         system.debug('== size '+documents.size());
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = testAccount.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
         
         Test.startTest();
         SubmitContractAdminController.updateContentVersion(testAccount.Id, documents[0].Id);
         Test.stopTest();
        
     }
   static testMethod void getCurrentAccountTestWithSomeValue02(){
        Branch__c obj =  new Branch__c(Name='test', Phone__c='889878788');
        insert obj;
        RecordType objRed = [SELECT DeveloperName,Id,Name FROM RecordType WHERE DeveloperName = 'Prospect_Account'];
        
        Account objAccount = new Account();
         objAccount.RecordTypeId = objRed.Id;
        objAccount.Name = 'test Account Contract Admin';       
        insert objAccount;
        
      	SubmitContractAdminController.checkMedatoryFieldAccount reponse = SubmitContractAdminController.getCurrentAccount(objAccount.Id);
      
        objAccount.Branch__c = obj.id;
        update objAccount;
        reponse = SubmitContractAdminController.getCurrentAccount(objAccount.Id);
        
         objAccount.FEIN__c = '1221';
        update objAccount;
        reponse = SubmitContractAdminController.getCurrentAccount(objAccount.Id);   
        
        objAccount.ShippingCity = 'test';
        update objAccount;
      reponse = SubmitContractAdminController.getCurrentAccount(objAccount.Id);
          objAccount.ShippingStreet = 'test';
        update objAccount;
         reponse = SubmitContractAdminController.getCurrentAccount(objAccount.Id);
         
    }


}