force-app/main/default/objects/Account/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to Branch object</description>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FEIN__c.field-meta.xml
<CustomField>
    <fullName>FEIN__c</fullName>
    <label>FEIN</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KAR_Createdbyid__c.field-meta.xml
<CustomField>
    <fullName>KAR_Createdbyid__c</fullName>
    <description>Created by ID for Buyer Service KAR account</description>
    <label>KAR Createdbyid</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KAR_ID__c.field-meta.xml
<CustomField>
    <fullName>KAR_ID__c</fullName>
    <description>Salesforce ID from KAR.</description>
    <externalId>true</externalId>
    <label>KAR ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/KAR_OwnerID__c.field-meta.xml
<CustomField>
    <fullName>KAR_OwnerID__c</fullName>
    <description>KAR Account owner ID from migrated buyer service account.</description>
    <label>KAR OwnerID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MergeDuplicateProspectKARBSAccount.cls
global class MergeDuplicateProspectKARBSAccount implements Database.batchable<sobject>, Database.Stateful{ 
  
    global Database.QueryLocator  start(Database.BatchableContext bc) {
   
    String query = System.Label.DuplicateaKAR_BS;    
    system.debug(' query '+query);             
        
        return Database.getQueryLocator(query);    
    }
    
 
    global void execute(Database.BatchableContext bc, List<Account> lstCon){
        
        system.debug('lstCon'+lstCon.size());
        for(Account masterCon: lstCon){
            findDuplicateKARBSAccount(masterCon);                
        }
    }
    
    global void finish(Database.BatchableContext bc){
    }
    
    private void findDuplicateKARBSAccount(Account objAccount){
        List<String> strFields = system.label.KAR_BS_Query.split(',');
        Id karBSAccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('KAR BS Account').getRecordTypeId();
        List<Account> lstDuplicateKARBSAccount = new List<Account>();
        lstDuplicateKARBSAccount = [SELECT id, KAR_Createdbyid__c, KAR_ID__c, KAR_OwnerID__c, FEIN__c, Branch__c, recordType.Name
                                    FROM Account
                                    WHERE KAR_ID__c != null AND KAR_ID__c =: objAccount.KAR_ID__c AND RecordTypeID =: karBSAccountRecordTypeId];
        list<list<Id>> lstDupAccIds = new list<list<Id>>();
        list<Id> dualList = new list<Id>();     
        system.debug('lstDuplicateKARBSAccount size '+lstDuplicateKARBSAccount.size());
        for(Account objAcc :lstDuplicateKARBSAccount){
            

            system.debug(objAcc);
            for(string str: strFields){
                 str=str.trim();
                system.debug('objAccount 1 '+objAccount);
                if((objAccount.get(str) == null || objAccount.get(str) == false)){
                    system.debug('Ass 1'+objAcc);
                    if(objAcc.get(str) != null && objAcc.get(str) != false){
                        system.debug('Ass 2'+objAcc);
                        objAccount.put(str, objAcc.get(str)); 
                        system.debug('objAccount 2 '+objAccount);
                    }
                }
            }
            
            if(dualList.size() <= 2){
                dualList.add(objAccount.Id);
                if(dualList.size() == 2){
                    lstDupAccIds.add(dualList);
                    dualList.clear();
                }
            }
            
        
        }
        system.debug('lstDupAccIds size '+lstDupAccIds.size());
        for(Account lst:lstDuplicateKARBSAccount){
            
            Database.Merge(objAccount,lst);
        }
        
    }
}