force-app/main/default/objects/Account/fields/Friday_Closed_At__c.field-meta.xml
<CustomField>
    <fullName>Friday_Closed_At__c</fullName>
    <label>Closed At</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Friday_Open_From__c.field-meta.xml
<CustomField>
    <fullName>Friday_Open_From__c</fullName>
    <label>Open From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Friday_Unavailable_From__c.field-meta.xml
<CustomField>
    <fullName>Friday_Unavailable_From__c</fullName>
    <label>Unavailable From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Friday_Unavailable_To__c.field-meta.xml
<CustomField>
    <fullName>Friday_Unavailable_To__c</fullName>
    <label>Unavailable To</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Location_Id__c.field-meta.xml
<CustomField>
    <fullName>Location_Id__c</fullName>
    <label>Location Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monday_Closed_At__c.field-meta.xml
<CustomField>
    <fullName>Monday_Closed_At__c</fullName>
    <label>Closed At</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monday_Open_From__c.field-meta.xml
<CustomField>
    <fullName>Monday_Open_From__c</fullName>
    <label>Open From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monday_Unavailable_From__c.field-meta.xml
<CustomField>
    <fullName>Monday_Unavailable_From__c</fullName>
    <label>Unavailable From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Monday_Unavailable_To__c.field-meta.xml
<CustomField>
    <fullName>Monday_Unavailable_To__c</fullName>
    <label>Unavailable To</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Saturday_Closed_At__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Closed_At__c</fullName>
    <label>Closed At</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Saturday_Open_From__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Open_From__c</fullName>
    <label>Open From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Saturday_Unavailable_From__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Unavailable_From__c</fullName>
    <label>Unavailable From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Saturday_Unavailable_To__c.field-meta.xml
<CustomField>
    <fullName>Saturday_Unavailable_To__c</fullName>
    <label>Unavailable To</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sunday_Closed_At__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Closed_At__c</fullName>
    <label>Closed At</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sunday_Open_From__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Open_From__c</fullName>
    <label>Open From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sunday_Unavailable_From__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Unavailable_From__c</fullName>
    <label>Unavailable From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sunday_Unavailable_To__c.field-meta.xml
<CustomField>
    <fullName>Sunday_Unavailable_To__c</fullName>
    <label>Unavailable To</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Thursday_Closed_At__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Closed_At__c</fullName>
    <label>Closed At</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Thursday_Open_From__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Open_From__c</fullName>
    <label>Open From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Thursday_Unavailable_From__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Unavailable_From__c</fullName>
    <label>Unavailable From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Thursday_Unavailable_To__c.field-meta.xml
<CustomField>
    <fullName>Thursday_Unavailable_To__c</fullName>
    <label>Unavailable To</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tuesday_Closed_At__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Closed_At__c</fullName>
    <label>Closed At</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tuesday_Open_From__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Open_From__c</fullName>
    <label>Open From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tuesday_Unavailable_From__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Unavailable_From__c</fullName>
    <label>Unavailable From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tuesday_Unavailable_To__c.field-meta.xml
<CustomField>
    <fullName>Tuesday_Unavailable_To__c</fullName>
    <label>Unavailable To</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wednesday_Closed_At__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Closed_At__c</fullName>
    <label>Closed At</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wednesday_Open_From__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Open_From__c</fullName>
    <label>Open From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wednesday_Unavailable_From__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Unavailable_From__c</fullName>
    <label>Unavailable From</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Account/fields/Wednesday_Unavailable_To__c.field-meta.xml
<CustomField>
    <fullName>Wednesday_Unavailable_To__c</fullName>
    <label>Unavailable To</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Case/fields/CRC_Storage_Location__c.field-meta.xml
<CustomField>
    <fullName>CRC_Storage_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Storage Location</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases (Storage Location)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <label>Public</label>
</RecordType>

force-app/main/default/classes/GetCaseInfoforCRC.cls
public class GetCaseInfoforCRC {
    @AuraEnabled(cacheable=true)
    public static Case getInfo( String recordId ){
        system.debug('==11='+recordId);
        Case caseList = [ Select Id, contact.Name, CRC_Storage_Location__r.Location_Id__c, CRC_Storage_Location__r.Type, CRC_Storage_Location__c, CRC_Storage_Location__r.ShippingAddress, Status, CRC_Storage_Location__r.Phone, CRC_Storage_Location__r.Fax, CRC_Storage_Location__r.Email__c, CRC_Storage_Location__r.Federal_Tax_Id__c,
                         CRC_Storage_Location__r.Sunday_Open_From__c, CRC_Storage_Location__r.Sunday_Closed_At__c, CRC_Storage_Location__r.Sunday_Unavailable_From__c, CRC_Storage_Location__r.Sunday_Unavailable_To__c, CRC_Storage_Location__r.Monday_Open_From__c,
                         CRC_Storage_Location__r.Monday_Closed_At__c, CRC_Storage_Location__r.Monday_Unavailable_From__c, CRC_Storage_Location__r.Monday_Unavailable_To__c, CRC_Storage_Location__r.Tuesday_Open_From__c, CRC_Storage_Location__r.Tuesday_Closed_At__c,
                         CRC_Storage_Location__r.Tuesday_Unavailable_From__c, CRC_Storage_Location__r.Tuesday_Unavailable_To__c, CRC_Storage_Location__r.Wednesday_Open_From__c, CRC_Storage_Location__r.Wednesday_Closed_At__c, CRC_Storage_Location__r.Wednesday_Unavailable_From__c,
                         CRC_Storage_Location__r.Wednesday_Unavailable_To__c, CRC_Storage_Location__r.Thursday_Open_From__c, CRC_Storage_Location__r.Thursday_Closed_At__c, CRC_Storage_Location__r.Thursday_Unavailable_From__c, CRC_Storage_Location__r.Thursday_Unavailable_To__c,
                         CRC_Storage_Location__r.Friday_Open_From__c, CRC_Storage_Location__r.Friday_Closed_At__c, CRC_Storage_Location__r.Friday_Unavailable_From__c, CRC_Storage_Location__r.Friday_Unavailable_To__c, CRC_Storage_Location__r.Saturday_Open_From__c, CRC_Storage_Location__r.Saturday_Closed_At__c,
                         CRC_Storage_Location__r.Saturday_Unavailable_From__c, CRC_Storage_Location__r.Saturday_Unavailable_To__c
                         from Case where Id=: recordId];
                         system.debug('==='+caseList);
    	return caseList;
    }
}