force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <description>Branch</description>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>Branch Name</description>
    <label>Branch Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Branch_Number__c</fullName>
    <description>Branch Number</description>
    <externalId>true</externalId>
    <label>Branch Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Admin Branch</description>
    <inlineHelpText>Admin Branch</inlineHelpText>
    <label>Branch Name</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Branch_number__c.field-meta.xml
<CustomField>
    <fullName>Branch_number__c</fullName>
    <description>Admin Branch Number</description>
    <inlineHelpText>Admin Branch Number</inlineHelpText>
    <label>Branch number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Payment_Branch__c.field-meta.xml
<CustomField>
    <fullName>Payment_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment_Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Stocks (Payment_Branch)</relationshipLabel>
    <relationshipName>Stocks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Payment_Branch_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Branch_Number__c</fullName>
    <description>User Story 500528: Stock/Stock Bid Fields for Lookup Association</description>
    <label>Payment Branch Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StockBranchNameUpdate.cls
global class StockBranchNameUpdate implements Database.batchable<sobject>, Database.Stateful{ 
    
    global Database.QueryLocator  start(Database.BatchableContext bc) {
        
        /*SELECT Branch_Name__c,payment_Branch_number__c , Branch_number__c, Id FROM Stock__c 
			WHERE (payment_Branch_number__c != null AND payment_Branch__c = Null) 
					OR (Branch_number__c != NULL AND Branch_Name__c = NULL)*/
        String query = System.Label.StockBranchUpdateQuery;    
        system.debug(' query '+query);             
        
        return Database.getQueryLocator(query);    
    }
    
    
    global void execute(Database.BatchableContext bc, List<Stock__c> lstStock){
        List<Stock__c> lstStockUpdate = new List<Stock__c>();
        List<String> BranchNumbers = new List<String>();
        Map<String,String> mapOfBranchNumAndBranchId = new Map<String,String>();
        for(Stock__c objStock : lstStock){
            if(objStock.Branch_number__c != NULL && objStock.Branch_Name__c == NULL){
                BranchNumbers.add(objStock.Branch_number__c);            
        	}
            if(objStock.payment_Branch_number__c != NULL && objStock.payment_Branch__c == NULL){
                BranchNumbers.add(objStock.payment_Branch_number__c);
            }
        }
        
        for(Branch__c objBranch : [SELECT Id, Name, Branch_Number__c From Branch__c WHERE Branch_Number__c IN: BranchNumbers]){
            mapOfBranchNumAndBranchId.put(objBranch.Branch_Number__c,objBranch.id);
        }
        for(Stock__c objStock :lstStock){
            if(mapOfBranchNumAndBranchId.containsKey(objStock.Branch_Number__c) && mapOfBranchNumAndBranchId.containsKey(objStock.payment_Branch_number__c)){
                objStock.Branch_Name__c = mapOfBranchNumAndBranchId.get(objStock.Branch_Number__c);
                objStock.Payment_Branch__c = mapOfBranchNumAndBranchId.get(objStock.Payment_Branch_number__c);
                lstStockUpdate .add(objStock);
            }else if(mapOfBranchNumAndBranchId.containsKey(objStock.payment_Branch_number__c)){
                 objStock.Payment_Branch__c = mapOfBranchNumAndBranchId.get(objStock.Payment_Branch_number__c);
                 lstStockUpdate .add(objStock);
            }else if(mapOfBranchNumAndBranchId.containsKey(objStock.Branch_Number__c)){
                objStock.Branch_Name__c = mapOfBranchNumAndBranchId.get(objStock.Branch_Number__c);
                lstStockUpdate .add(objStock);
            }
        }
        if(!lstStockUpdate.isEmpty()){
            update lstStockUpdate ;
        }
    }
    
    global void finish(Database.BatchableContext bc){
    }
    
    
}