force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Buyer_ID__c.field-meta.xml
<CustomField>
    <fullName>Buyer_ID__c</fullName>
    <description>Buyer&apos;s ASAP ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Buyer&apos;s ASAP ID</inlineHelpText>
    <label>Buyer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Buyers Name</description>
    <inlineHelpText>Buyers Name</inlineHelpText>
    <label>Buyer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>Provider_ID__c</fullName>
    <description>Provider&apos;s ASAP ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Provider&apos;s ASAP ID</inlineHelpText>
    <label>Provider ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>Provider_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Provider&apos;s Name</description>
    <inlineHelpText>Provider&apos;s Name</inlineHelpText>
    <label>Provider Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stocks (Provider Name)</relationshipLabel>
    <relationshipName>Stocks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StockBuyProIdUpdateBatch.cls
global class StockBuyProIdUpdateBatch implements Database.Batchable<sObject> {
  
    global Database.QueryLocator start(Database.BatchableContext BC) {
       
         
        /*SELECT Id,Buyer_ID__c, Buyer_Name__c,Provider_ID__c, Provider_Name__c FROM Stock__c 
		  WHERE ((Buyer_ID__c != null AND (NOT Buyer_Id__c like 'BUY-%'))
				Or (Provider_ID__c != null  AND (NOT Provider_ID__c Like 'PRO-%'))); */
        
		String query = Label.StockBuyProPrefixIdUpdateQuery;
		system.debug('query  = '+query);
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<Stock__c> stockList) {       
		List<Stock__c> lstStockUpdate = new List<Stock__c>();
         system.debug('stockList size = '+stockList.size());  
        for(Stock__c objTempStock : stockList){
            system.debug(' objTempStock '+objTempStock.Id);
			if(String.isNotBlank(objTempStock.Buyer_ID__c) && String.isNotBlank(objTempStock.Provider_ID__c) && !objTempStock.Buyer_ID__c.startsWithIgnoreCase('BUY-') 
               && !objTempStock.Provider_ID__c.startsWithIgnoreCase('PRO-')){
				objTempStock.Buyer_ID__c = 'BUY-'+objTempStock.Buyer_ID__c;
				objTempStock.Provider_ID__c = 'PRO-'+objTempStock.Provider_ID__c;
				lstStockUpdate.add(objTempStock);
			}else if(String.isNotBlank(objTempStock.Buyer_ID__c) && !objTempStock.Buyer_ID__c.startsWithIgnoreCase('BUY-')){
				objTempStock.Buyer_ID__c = 'BUY-'+objTempStock.Buyer_ID__c;
				lstStockUpdate.add(objTempStock);
			}else if(String.isNotBlank(objTempStock.Provider_ID__c) && !objTempStock.Provider_ID__c.startsWithIgnoreCase('PRO-')){
				objTempStock.Provider_ID__c = 'PRO-'+objTempStock.Provider_ID__c;
				lstStockUpdate.add(objTempStock);
			}
			
		}
        system.debug('lstStockUpdate size = '+lstStockUpdate.size());
        
        try {
            if(!lstStockUpdate.isEmpty()){
				update lstStockUpdate;
			}
		} catch(Exception e) {
            System.debug(e);
        }
         
    }   
     
    global void finish(Database.BatchableContext BC) {    
        database.executeBatch(new StockAccountAssociationBatch());
  }
}