force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Buyer_Name__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Buyers Name</description>
    <inlineHelpText>Buyers Name</inlineHelpText>
    <label>Buyer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/VIN__c.field-meta.xml
<CustomField>
    <fullName>VIN__c</fullName>
    <description>Vehicle Identification Number</description>
    <inlineHelpText>Vehicle Identification Number</inlineHelpText>
    <label>VIN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IAAI_UpdateVPEListingWithStockScheduTest.cls
@isTest
private class IAAI_UpdateVPEListingWithStockScheduTest{
    @testSetup
    static void setup() {
        //Test Data Setup
        Account testAccount = new Account(Name='Test Account 1');
        insert testAccount;
        
        List<VPE_Listings__c> vpeListingList = new List<VPE_Listings__c>();
        List<Stock__c> stockListingList = new List<Stock__c>();
        for(Integer i=1; i<=10; i++){
            vpeListingList.add(new VPE_Listings__c(VIN__c = String.valueOf(i)));
            stockListingList.add(new Stock__c(Name= 'Test Stock ' + i, Buyer_Name__c=testAccount.Id, VIN__c = String.valueOf(i)));
        }
        if(!vpeListingList.isEmpty()){
            insert vpeListingList;
        }
        if(!stockListingList.isEmpty()){
            insert stockListingList;
        }
    }

    @isTest
    static void testMethod1(){
        Test.startTest();
            String jobId = System.schedule('IAAI_UpdateVPEListingWithStockScheduTest', '0 0 0 15 3 ? 2022', new IAAI_UpdateVPEListingWithStockScheduler());
        Test.stopTest();
    }
}