force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Buyer_ID__c.field-meta.xml
<CustomField>
    <fullName>Buyer_ID__c</fullName>
    <description>Buyer&apos;s ASAP ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Buyer&apos;s ASAP ID</inlineHelpText>
    <label>Buyer ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Provider_ID__c.field-meta.xml
<CustomField>
    <fullName>Provider_ID__c</fullName>
    <description>Provider&apos;s ASAP ID</description>
    <externalId>true</externalId>
    <inlineHelpText>Provider&apos;s ASAP ID</inlineHelpText>
    <label>Provider ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StockBuyerIdProviderIdCorrectionBatch.cls
global class StockBuyerIdProviderIdCorrectionBatch implements Database.Batchable<sObject> {
  
    global Database.QueryLocator start(Database.BatchableContext BC) {
       
         
        //String query = 'SELECT Id,Buyer_ID__c, Provider_ID__c  FROM Stock__c WHERE (Buyer_ID__c!= null OR Provider_ID__c!=null) and CreatedDate = today';
      String query = Label.StockBuyerIdProviderIdCorrectionTodayQuery;
       system.debug('query***'+query);
       
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<Stock__c> stockList) {
        
     
       
        List<Stock__c> lstStockToUpdate = new List<Stock__c>();
        boolean containFlag  = false;
        
        for(Stock__c stk : stockList){ 
            
            if(stk.Buyer_ID__c!= null && !stk.Buyer_ID__c.startsWith('BUY-')){

                stk.Buyer_ID__c = 'BUY-'+stk.Buyer_ID__c;
                containFlag = true ;
                
            }
            if(stk.Provider_ID__c!= null && !stk.Provider_ID__c.startsWith('PRO-')){
                
                stk.Provider_ID__c = 'PRO-'+stk.Provider_ID__c;
                containFlag = true ;               
            }
            
            if(containFlag){
               lstStockToUpdate.add(stk); 
               containFlag = false;
            }       
            
        }
        
        
        try {
            // Update the Stock Record
            update lstStockToUpdate;
            
         
        } catch(Exception e) {
            System.debug(e);
        }
         
    }   
     
    global void finish(Database.BatchableContext BC) {       
  }
}