force-app/main/default/objects/Contact/fields/Buyer_Employee_ID__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Employee_ID__c</fullName>
    <label>Buyer Employee ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Public.recordType-meta.xml
<RecordType>
    <fullName>Public</fullName>
    <active>true</active>
    <label>Public</label>
</RecordType>

force-app/main/default/objects/Stock__c/Stock__c.object-meta.xml
<CustomObject>
    <label>Stock</label>
    <nameField>
        <label>Stock Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stocks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <description>Reference to the sold stock.</description>
    <externalId>true</externalId>
    <inlineHelpText>Reference to the sold stock.</inlineHelpText>
    <label>Stock #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock__c/fields/Stock_Bid__c.field-meta.xml
<CustomField>
    <fullName>Stock_Bid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stock Bid</label>
    <referenceTo>Stock_Bid__c</referenceTo>
    <relationshipLabel>Stocks</relationshipLabel>
    <relationshipName>Stocks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StockBidContactAssociationBatch_Test.cls
@isTest
public class StockBidContactAssociationBatch_Test {
    static testMethod void StockBidContactBatch_Test1(){
       stock__c objStk = new Stock__c(Name='12351235');
        insert objStk;
       Stock_Bid__c objSB = new Stock_Bid__c(Buyer_Employee_Id__c = '12345',Stock__c = '12351235');
       insert objSB;
        
       Contact objCon = new Contact(LastName = 'TestCon', Buyer_Employee_Id__c = '12345');
        insert objCon;
        
        Test.startTest();
        StockBidContactAssociationBatch objSBCAB = new StockBidContactAssociationBatch();
         DataBase.executeBatch(objSBCAB);

        Test.stopTest();

    }

}